# Network sufficient to memorize data
layer_type: "continuous"
normalize: true

# Number of characters as input
features: 16

model_type: high_order
n: 2
n_in: 2
n_out: null
n_hidden: null
periodicity: 2.0
rescale_output: False
input:
  segments: 128
  width: ${mlp.features}
output:
  segments: 2
  width: 128
hidden:
  segments: 2
  layers: 1
  width: 250
