# Network sufficient to memorize data
layer_type: "continuous"
normalize: layer

# Number of characters as input
features: 16

model_type: high_order
n: 2
n_in: 2
n_out: null
n_hidden: null
periodicity: 2.0
rescale_output: False
segments: 2
input:
  layer_type: continuous
  segments: 128
  width: ${net.features}
output:
  segments: ${net.segments}
  width: 128
hidden:
  segments: ${net.segments}
  layers: 1
  width: 250
