# Large network where only the input uses a segmented
# layer.
model_type: high_order_input
layer_type: discontinuous
normalize: layer

# Number of characters as input
features: 16

# Polynomial interpolation points.  Polynomial order
# is (n-1).  In the case of Fourier series, n is the
# number of Fourier components.
n: 2
n_in: 2
periodicity: 2.0
rescale_output: False
input:
  layer_type: continuous
  segments: 128
  width: ${net.features}
output:
  width: 128
hidden:
  layers: 1
  width: 250
