layer_type: "continuous1d"
normalize: true
rescale_output: False

# Number of characters as input. Convnet can
# have a much larger context
features: 256
out_features: 128 # ascii characters

model_type: high_order_tail_focus

n: 2
periodicity: 2.0
kernel_size: [16, 16]
stride: [8, 8]
channels: [1, 500, 100]
segments: [128, 2]

# The first element is the input which we don't want in this case
focus: [0, 16] # focus takes all of the final output
