layer_type: "continuous1d"
normalize: true

# Number of characters as input. Convnet can
# have a much larger context
features: 10000
out_features: 128 # ascii characters

model_type: high_order_tail_focus

n: 2
periodicity: 2.0
kernel_size: [10, 10, 10, 10]
stride: [10, 10, 10, 10]
channels: [1, 10, 100, 100]
segments: [128, 10, 10, 10]
focus: [10, 10, 10, 10] # focus takes all of the final output
