# Small network that runs pretty fast.  See at
# most 50% accuracy.

layer_type: "continuous"
normalize: false

# Polynomial interpolation points.  Polynomial order
# is (n-1).  In the case of Fourier series, n is the
# number of Fourier components.
model_type: high_order_transformer
n: 3
input_segments: 64
segments: 2
# Layers in the form [input, output, segments]

# attention blocks
#layers: [[10, 10, 64], [10, 5, 2], [5, 5, 2]]
inner: 10
#layers: [[1, ${inner}, 128], [${inner}, ${inner}, 10], [${inner}, ${inner}, 10]]
layers: [[1, 8, 128], [8, 8, 4], [8, 8, 4], [8, 8, 4], [8, 8, 4]]

output_layer:
  segments: 10
  hidden_layers: 1
  hidden_width: 100

# Note! output dimension is c=heads*output so different than normal
# And then similarity size is c*c*batch_size

heads: 100
