# Small network that runs pretty fast.  See at
# most 50% accuracy.

layer_type: "discontinuous"
normalize: true

# Polynomial interpolation points.  Polynomial order
# is (n-1).  In the case of Fourier series, n is the
# number of Fourier components.
model_type: high_order_transformer
n: 3
input_segments: 64
segments: 2
# Layers in the form [input, output, segments]
layers: [[10, 10, 64], [10, 5,2], [5, 5, 2]]
