# Small network that runs pretty fast.  See at
# most 50% accuracy.

layer_type: continuous
normalize: layer #maxabs

# Polynomial interpolation points.  Polynomial order
# is (n-1).  In the case of Fourier series, n is the
# number of Fourier components.
model_type: high_order_transformer
n: 3

segments: 2
base_width: 8

# attention blocks
inner: 10

layers:
  - input: 1
    hidden: 16
    output: 8
    layers: 1
    segments: ${net.segments}
    input_segments: 128

  - input: 8
    output: ${net.base_width}
    segments: ${net.segments}

  - input: ${net.base_width}
    output: ${net.base_width}
    segments: ${net.segments}

  - input: ${net.base_width}
    output: ${net.base_width}
    segments: ${net.segments}

  - input: ${net.base_width}
    hidden: 100
    layers: 1
    segments: ${net.segments}

# Note! output dimension is c=heads*output so different than normal
# And then similarity size is c*c*batch_size

heads: 4
