filenames:
  - "books/frankenstein.txt"
  - "books/the_raven.txt"

# fully convolutional layers
fcn:
  layer_type: ["continuous1d", "continuous1d"]
  normalize: false

  # Number of characters as input
  features: 16
  n: [3, 3]
  channels: [2, 2, 2]
  segments: [2, 2]
  kernel_size: [2, 2]
  periodicity: 2.0
  rescale_output: False

# fully connected output layer
out:
  layer_type: "discontinuous"
  n: 2
  segments: 2

normalize: false

data:
  type: sequence # centered
  reapply: 10 # number of times to reapply calculation
  max_size: -1

max_epochs: 50
gpus: 1
lr: 1e-4
batch_size: 256
gradient_clip: null # 5.0

# Are you training? Otherwise plot the result
train: True
checkpoint: null
rotations: 1 # 1 is x,y, 2 is x,y, x-y, x+y, greater includes additional rotations

text: "This is sample text"
topk: 5
num_predict: 100

defaults:
  - override hydra/sweeper: nevergrad

hydra:
  sweeper:
    optim:
      # name of the nevergrad optimizer to use
      # OnePlusOne is good at low budget, but may converge early
      optimizer: OnePlusOne
      # total number of function evaluations to perform
      budget: 40
      # number of parallel workers for performing function evaluations
      num_workers: 10
      # maximize: true  # comment out for maximization
    # default parametrization of the search space
    parametrization:
      fcn.n:
        init: 3
        lower: 2
        upper: 3
        integer: true
      fcn.layer_type:
        - continuous1d
        - discontinuous1d
